spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        filters:
          - name: RequestRateLimiter
            args:
              key-resolver: "#{@hostAddrKeyResolver}"
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 3
                - StripPrefix=1

  redis:
    host: localhost
    port: 6379
server:
  port: 20020