spring:
  zipkin:
    base-url: http://localhost:30001
    sender:
      type: web
  application:
    name: consul-consumer-feign
  cloud:
    consul:
      host: localhost
      port: 8500
server:
  port: 10014

feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:10010/eureka/